service: price-history
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: "us-east-1"
  profile: "dazes-serverless"
  deploymentMethod: "direct"
  deploymentPrefix: "serverless"
  stage: ${opt:stage, self:provider.stage, "dev"}
  httpApi:
    name: ${self.custom.apiGatewayName}
    cors: true

functions:
  priceHistoryApi:
    handler: index.priceHistory
    description: "API to obtain price history data"
    memorySize: 512
    events:
      - httpApi:
          path: /
          method: GET

  priceHistoryWatcher:
    handler: index.priceHistoryScheduler
    description: "Scheduler to obtain price history data"
    memorySize: 128
    events:
      - schedule:
          name: scheduler-binance
          description: scheduler to obtain data from binance
          rate: rate(10 minutes)
          enabled: false

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  apiGatewayName: ${opt:stage, "dev"}-${self.service}
